Repository MAAGE-BRC/MAAGE-Web, pull requests merged in 2025-05, with the labels that each got.

#33 chris-c-thomas/dev --> MAAGE-BRC/dev
  .gitignore
  README.md
  package.json
  postcss.config.js
  public/js/p3/app/app.js
  public/js/p3/widget/search/templates/TaxaSearch-dev.html
  public/maage/css/dist/maage.css
  public/maage/css/dist/maage.min.css
  public/maage/css/src/index-dev.css
  public/maage/css/src/index.css
  public/maage/css/src/partials/dashboards.css
  public/maage/css/src/partials/footer.css
  public/maage/css/src/partials/header.css
  public/maage/css/src/partials/homepage.css
  public/maage/css/src/partials/navbar.css
  public/maage/css/src/partials/pages.css
  public/maage/css/src/partials/reset-utils.css
  public/maage/css/src/partials/typography.css
  public/maage/css/src/partials/variables.css
  public/maage/css/src/styles.css
  public/maage/css/src/tailwind.css
  public/maage/css/src/tailwindcss/output.css
  tailwind.config.js
  views/dev/adv-search-genome.ejs
  views/footer.ejs
  views/head.ejs
  views/home.ejs
  views/navbar.ejs
Labels: impact: low, area: frontend, area: ux, env: dev, deploy on: dev

#37 Dev - MAAGE - Whole Genome SNP
  public/js/p3/widget/app/WholeGenomeSNPAnalysis.js
  public/js/p3/widget/app/templates/WholeGenomeSNPAnalysis.html
Labels: status: ready for merge, status: done, type: feature, env: dev, deploy on: dev

#38 chore: bump MAAGE v0.5.15
  package.json
Labels: env: prod
